version: "3"
services:
  lego-mongo:
    image: mongo
    container_name: lego-mongo
    volumes:
      - ".docker-volumes/mongo/data:/data/db"
      - "$PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d/"
    ports:
      - 27018:27017
    env_file:
      - .env
  lego-redis:
    image: redis:6
    container_name: lego-redis
    command: >
      --requirepass ${REDIS_PASSWORD}
    ports:
      - 6378:6379
    env_file:
      - .env
  lego-backend:
    image: registry.cn-hangzhou.aliyuncs.com/vikingmute/lego:{{tag}}
    container_name: lego-backend
    ports:
      - 7002:7001
    env_file:
      - .env
